# Generated by Django 5.2.7 on 2025-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
