# Generated by Django 5.2.6 on 2025-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
