# Generated by Django 5.2.6 on 2025-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrders', '0002_ordersmodel_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
