# Generated by Django 5.2.6 on 2025-11-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrders', '0003_ordersmodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='phone_number',
        ),
    ]
