# Generated by Django 5.2.7 on 2025-10-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAccounts', '0001_initial'),
        ('appBooks', '0003_booksmodel_ispn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBooks.booksmodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.accountmodel')),
            ],
        ),
    ]
