# Generated by Django 5.2.7 on 2025-11-04 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0002_accountmodel_username_alter_accountmodel_email_and_more'),
        ('appBooks', '0004_remove_booksmodel_id_remove_booksmodel_ispn_and_more'),
        ('appCart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='ispn',
            new_name='isbn',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart_email', to='appAccounts.accountmodel'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_username', to='appAccounts.accountmodel'),
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.UniqueConstraint(fields=('username', 'email', 'ispn'), name='unique_cart'),
        ),
    ]
