# Generated by Django 5.2.7 on 2025-11-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='accountmodel',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
