# Generated by Django 5.2.7 on 2025-11-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0002_accountmodel_username_alter_accountmodel_email_and_more'),
        ('appAccounts', '0002_usermodel_delete_user'),
    ]

    operations = [
    ]
