# Generated by Django 5.2.6 on 2025-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='coverImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
