# Generated by Django 5.2.7 on 2025-10-23 01:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0002_booksmodel_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='ispn',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
