# Generated by Django 5.2.6 on 2025-10-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0002_booksmodel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/covers/'),
        ),
    ]
