# Generated by Django 5.2.6 on 2025-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0002_alter_booksmodel_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='coverImage',
            field=models.ImageField(upload_to='media/covers/'),
        ),
    ]
