# Generated by Django 5.2.7 on 2025-11-04 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0003_booksmodel_ispn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booksmodel',
            name='ispn',
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='isbn',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
