# Generated by Django 5.2.6 on 2025-10-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0003_booksmodel_ispn'),
        ('appBooks', '0004_alter_booksmodel_cover_image'),
    ]

    operations = [
    ]
