# Generated by Django 5.2.7 on 2025-11-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBooks', '0004_remove_booksmodel_id_remove_booksmodel_ispn_and_more'),
        ('appBooks', '0005_merge_20251022_2139'),
    ]

    operations = [
    ]
